version: '2'

services:
  db:
    image: postgres
    restart: always
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && python3 manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - MyURLSaverProdKey=1111111
    depends_on:
      - db
    restart: always
