version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && gunicorn MyURLSaver.wsgi:application"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      - MyURLSaverProdKeyDEBUG=1
      - MyURLSaverProdKey=1111111
    depends_on:
      - db
